---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: mx-client
  template:
    metadata:
      labels:
        app: mx-client
    spec:
      containers:
      - name: client
        image: localhost:32000/client
        imagePullPolicy: Always
        env:
        - name: SRVURL
          value: http://server:8000
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 150Mi
