---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: server-scaler
spec:
  scaleTargetRef:
    name: server
  # let's set pretty aggressive scaling timings, according to our 2min client lifetime.
  pollingInterval: 4
  cooldownPeriod:  10
  minReplicaCount: 1
  maxReplicaCount: 15
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 45 # wait 45s to confirm that we can really scale down our infrastructure
          policies:
          - type: Percent
            value: 66         # don't scale down too fast to produce some visible & progressive results in dashboards
            periodSeconds: 15 # same here
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      metricName: total_server_conn_count
      threshold: "10"
      query: sum(mx_server_active_conn_gauge{app="mx-server"})
