{
 "title": "Madbox Server App Metrology",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean Processed FPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mx_server_processed_fps_total{app=\"mx-server\"}[20s])) / count(nodejs_version_info{app=\"mx-server\"})",
     "legendFormat": "mean FPS"
    }
   ]
  },
  {
   "title": "Total App Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mx_server_active_conn_gauge{app=\"mx-server\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(nodejs_version_info{app=\"mx-server\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mx_server_handled_conn_total{app=\"mx-server\"}[20s]))",
     "legendFormat": "conn/sec"
    }
   ]
  },
  {
   "title": "Mean Connections Per Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mx_server_active_conn_gauge{app=\"mx-server\"}) / count(nodejs_version_info{app=\"mx-server\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Per Instance Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "FPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mx_server_processed_fps_total{app=\"mx-server\"}[20s])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "New Conns / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mx_server_handled_conn_total{app=\"mx-server\"}[20s])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Active Conns",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mx_server_active_conn_gauge{app=\"mx-server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}