---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: mx-server
  template:
    metadata:
      labels:
        app: mx-server
    spec:
      containers:
      - name: server
        image: localhost:32000/server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  selector:
    app: mx-server
  ports:
  - name: http
    port: 8000
    targetPort: http
