---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: mx-server
spec:
  selector:
    matchLabels:
      app: mx-server
  template:
    metadata:
      labels:
        app: mx-server
    spec:
      containers:
      - name: server
        image: localhost:32000/server
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 0
          periodSeconds: 1
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: http
          containerPort: 8000
        # # use this for running perfectly safe (empirical resources fitting)
        # resources:
        #   limits:
        #     cpu: 750m
        #     memory: 1900Mi
        #   requests:
        #     cpu: 750m
        #     memory: 1900Mi

        # use this when running autoscaler mode, because it helps going wild & scale more instances on my laptop
        # some app crashes & OOM kill may happen
        resources:
          limits:
            cpu: 650m
            memory: 850Mi
          requests:
            cpu: 650m
            memory: 850Mi

---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: mx-server
spec:
  type: LoadBalancer
  selector:
    app: mx-server
  ports:
  - name: http
    port: 8000
    targetPort: http
