---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 15m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.30.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1m
  test:
    enable: true
  values: {}
