---
apiVersion: v1
kind: Namespace
metadata:
  name: keda-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kedacore-charts
  namespace: default
spec:
  interval: 10m
  url: https://kedacore.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: default
spec:
  interval: 5m
  releaseName: keda
  targetNamespace: keda-system
  storageNamespace: keda-system
  chart:
    spec:
      chart: keda
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: kedacore-charts
      interval: 1m
  values: {}
